defmodule GlobalCombatWeb.GameLive.MapGeometry do
  @moduledoc """
  Per-map SVG metadata for `GameLive.WorldMap` — GENERATED by `scripts/trace_maps.py`
  together with the `world_map/<map>_map_defs.html.heex` templates (territory
  outlines and links as static SVG `<defs>`). Do not edit by hand.

  Everything is traced from the legacy ASP.NET project's `Web/wwwroot/maps/<map>/
  <tech>0.gif` silhouettes (the LiveView app no longer ships those sprites) placed at
  their `MapInfo.render_info/2` offsets, so the shapes and the legacy 800x480 board
  coordinates are exactly the sprite board's; only the rendering changes (vector fills
  styled by CSS instead of nine pre-colored GIFs per territory). Links come from
  `MapInfo` adjacency — any two linked areas whose silhouettes are more than a few
  pixels apart get a line between their closest boundary points (sea lanes on the world
  map, where Alaska <-> Pevek wraps off the board edges; the arrow routes on elements).
  The legacy masks overlap slightly. Each covered pixel is assigned to the nearest
  territory label anchor, then territory fills are traced from that shared partition.

  A label anchor is the approximate pole of inaccessibility (last pixels to survive
  repeated erosion), so army counts land inside the widest part of a territory —
  not at the bounding-box center, which for Alaska or Indonesia falls in the sea.

  Regenerate (from `liveview/`):

      python3 -m venv .venv && .venv/bin/pip install pillow numpy
      .venv/bin/python scripts/trace_maps.py . && mix format
  """

  @view_boxes %{
    original: "0 0 800 480",
    elements: "236 54 456 421"
  }

  @doc "SVG `viewBox` for `map_name` — the world map fills the legacy 800x480 board, elements is cropped to its art."
  def view_box(map_name), do: Map.fetch!(@view_boxes, map_name)

  @labels %{
    original: %{
      1 => {163.5, 144.5},
      2 => {266.2, 118.2},
      3 => {200.5, 172.5},
      4 => {250.0, 185.5},
      5 => {314.2, 190.2},
      6 => {226.8, 232.8},
      7 => {281.8, 235.5},
      8 => {239.8, 264.4},
      9 => {387.3, 102.5},
      10 => {301.5, 314.5},
      11 => {311.5, 361.0},
      12 => {339.1, 346.1},
      13 => {310.5, 404.5},
      14 => {440.0, 293.0},
      15 => {484.9, 295.9},
      16 => {475.0, 334.5},
      17 => {498.5, 356.5},
      18 => {484.5, 396.5},
      19 => {531.9, 383.3},
      20 => {418.2, 164.5},
      21 => {431.5, 218.5},
      22 => {442.5, 233.5},
      23 => {463.5, 226.5},
      24 => {492.0, 156.3},
      25 => {493.3, 226.9},
      26 => {535.5, 196.5},
      27 => {524.3, 273.1},
      28 => {555.2, 231.2},
      29 => {594.0, 288.7},
      30 => {590.2, 184.8},
      31 => {627.1, 127.3},
      32 => {650.6, 248.4},
      33 => {637.5, 294.5},
      34 => {692.7, 200.3},
      35 => {664.5, 163.2},
      36 => {704.8, 160.0},
      37 => {744.0, 158.5},
      38 => {746.5, 232.5},
      39 => {671.0, 341.8},
      40 => {672.5, 402.5},
      41 => {713.5, 411.0},
      42 => {724.2, 369.1}
    },
    elements: %{
      1 => {463.5, 176.5},
      2 => {375.2, 264.8},
      3 => {464.5, 353.5},
      4 => {552.5, 265.5},
      5 => {419.5, 221.0},
      6 => {509.0, 309.5},
      7 => {640.5, 177.5},
      8 => {530.0, 110.0},
      9 => {397.3, 110.3},
      10 => {499.5, 212.5},
      11 => {516.5, 151.0},
      12 => {490.0, 124.5},
      13 => {437.5, 123.5},
      14 => {410.5, 150.5},
      15 => {641.5, 354.5},
      16 => {619.0, 331.5},
      17 => {618.3, 199.7},
      18 => {517.5, 231.0},
      19 => {579.0, 317.5},
      20 => {605.5, 291.5},
      21 => {605.0, 240.0},
      22 => {578.5, 213.5},
      23 => {287.5, 177.5},
      24 => {309.3, 199.3},
      25 => {310.0, 331.0},
      26 => {411.0, 300.0},
      27 => {349.0, 212.5},
      28 => {322.8, 238.8},
      29 => {323.5, 290.5},
      30 => {350.3, 316.7},
      31 => {287.5, 352.5},
      32 => {398.0, 420.5},
      33 => {531.0, 420.0},
      34 => {429.0, 318.5},
      35 => {412.0, 380.0},
      36 => {438.8, 406.2},
      37 => {490.8, 405.8},
      38 => {517.0, 379.5}
    }
  }

  @doc "`{x, y}` army-count anchor for area `number` on `map_name`."
  def label(map_name, number), do: @labels |> Map.fetch!(map_name) |> Map.fetch!(number)

  @elements %{
    1 => :fire,
    2 => :wind,
    3 => :earth,
    4 => :water,
    5 => nil,
    6 => nil,
    7 => :fire,
    8 => :fire,
    9 => :fire,
    10 => :fire,
    11 => :fire,
    12 => :fire,
    13 => :fire,
    14 => :fire,
    15 => :water,
    16 => :water,
    17 => :water,
    18 => :water,
    19 => :water,
    20 => :water,
    21 => :water,
    22 => :water,
    23 => :wind,
    24 => :wind,
    25 => :wind,
    26 => :wind,
    27 => :wind,
    28 => :wind,
    29 => :wind,
    30 => :wind,
    31 => :earth,
    32 => :earth,
    33 => :earth,
    34 => :earth,
    35 => :earth,
    36 => :earth,
    37 => :earth,
    38 => :earth
  }

  @doc "The element (`:fire | :water | :wind | :earth`) an elements-map area belongs to, `nil` for the bridges and for every world-map area."
  def element(:elements, number), do: Map.fetch!(@elements, number)
  def element(_map_name, _number), do: nil
end
