defmodule GlobalCombatWeb.GameLive.OriginalMapGeometry do
  @moduledoc """
  Per-area label anchors for the `:original` world map's SVG board — GENERATED by
  `scripts/trace_original_map.py` together with its sibling
  `world_map/original_map_defs.html.heex` (the territory outlines, sea lanes and
  region borders as static SVG `<defs>`). Do not edit either by hand.

  Everything is traced from the legacy `priv/static/maps/original/<tech>0.gif`
  silhouettes placed at their `MapInfo.render_info/2` offsets, so the shapes and the
  800x480 coordinate space are exactly the sprite board's; only the rendering changes
  (vector fills styled by CSS instead of nine pre-colored GIFs per territory). Sea
  lanes come from `MapInfo` adjacency — any two linked areas whose silhouettes do not
  touch get a lane between their closest coast points (Alaska <-> Pevek wraps off
  the board edges). Region borders are the traced union of each region's areas.

  A label anchor is the approximate pole of inaccessibility (last pixels to survive
  repeated erosion), so army counts land inside the widest part of a territory —
  not at the bounding-box center, which for Alaska or Indonesia falls in the sea.

  Regenerate (from `liveview/`):

      python3 -m venv .venv && .venv/bin/pip install pillow numpy
      .venv/bin/python scripts/trace_original_map.py . && mix format
  """

  @view_box "0 0 800 480"

  @doc "SVG `viewBox` the defs template and the anchors below are expressed in."
  def view_box, do: @view_box

  @labels %{
    1 => {163.5, 144.5},
    2 => {266.2, 118.2},
    3 => {200.5, 172.5},
    4 => {250.0, 185.5},
    5 => {314.2, 190.2},
    6 => {226.8, 232.8},
    7 => {281.8, 235.5},
    8 => {239.8, 264.4},
    9 => {387.3, 102.5},
    10 => {301.5, 314.5},
    11 => {311.5, 361.0},
    12 => {337.5, 347.5},
    13 => {310.5, 404.5},
    14 => {441.0, 293.0},
    15 => {484.9, 295.9},
    16 => {475.4, 333.8},
    17 => {498.5, 356.5},
    18 => {484.5, 396.5},
    19 => {531.9, 383.3},
    20 => {418.2, 164.5},
    21 => {431.5, 218.5},
    22 => {442.5, 233.5},
    23 => {461.5, 224.4},
    24 => {492.0, 156.3},
    25 => {493.1, 227.5},
    26 => {539.0, 189.8},
    27 => {524.3, 273.1},
    28 => {555.2, 231.2},
    29 => {594.0, 288.7},
    30 => {590.2, 184.8},
    31 => {627.1, 127.3},
    32 => {650.5, 249.5},
    33 => {637.5, 294.5},
    34 => {692.7, 200.3},
    35 => {665.0, 164.0},
    36 => {705.0, 160.5},
    37 => {744.0, 158.5},
    38 => {746.5, 232.5},
    39 => {671.0, 341.8},
    40 => {672.5, 402.5},
    41 => {713.5, 411.0},
    42 => {724.2, 369.1}
  }

  @doc "`{x, y}` army-count anchor for area `number`."
  def label(number), do: Map.fetch!(@labels, number)
end
