defmodule GlobalCombatWeb.GameLive.WorldMap do
  @moduledoc """
  Vector board for the `:original` world map — replaces the per-territory GIF
  sprites (`priv/static/maps/original/<tech><owner>.gif`, nine pre-colored 8-bit
  tiles per area) with one responsive SVG whose territories are `<use>` clones
  of static `<defs>` outlines, filled by CSS from the owner number.

  Why a rewrite rather than a restyle: the sprites baked owner color into pixels,
  so they could not be themed, could not show a selection state beyond a box
  outline, rendered blurry on any display density above 1x, and the LiveView
  port had also dropped the two overlay layers the legacy `Index.cshtml` drew
  (sea lanes and the Europe/Asia divider) — leaving no visible cue that Alaska
  reaches Pevek or Brazil reaches Algeria. Here the lanes are derived from the
  same `MapInfo` adjacency the rules use, so they can never disagree with it.

  Layering (paint order, bottom to top): sea → sea lanes → territories (the only
  interactive layer) → region borders → selected/target highlight → army counts.
  The highlight is a second `<use>` of the same outline drawn *above* the
  neighbours so a selected coastline is never half-covered by the territory
  painted after it, over a wider surface-coloured halo so the ring reads even
  where the owner fill happens to match the focus-ring or danger hue.

  Geometry (`world_map/original_map_defs.html.heex`, `OriginalMapGeometry`) is
  generated by `scripts/trace_original_map.py` from the legacy silhouettes, so
  shapes, adjacency and the 800x480 coordinate space are unchanged from the
  sprite board. The defs are a static template: LiveView ships them once with
  the page statics and never re-sends them on a diff, however often ownership
  changes.

  Accessibility: each territory is a `role="button"` group with an
  `aria-label` carrying name, owner and army count (or "hidden by fog of war")
  and `aria-pressed` for the selected/target state; Enter and Space activate it
  through the colocated `.TerritoryKeyboard` hook since SVG has no native
  button. The army-count text is decorative (`aria-hidden`, the label already
  says it) and gets a dark stroke under a light fill via `paint-order: stroke`
  so it stays legible on every owner colour (GIF-83). `GameLive.board_table/1`
  remains the tabular equivalent for screen readers (GIF-81).
  """
  use Phoenix.Component

  alias GlobalCombatWeb.GameLive.OriginalMapGeometry, as: Geometry

  embed_templates "world_map/*"

  attr :areas, :list, required: true, doc: "`PlayerView.areas` — already fog-filtered"
  attr :players, :list, required: true, doc: "`PlayerView.players`, for owner names"
  attr :selected_area, :any, required: true, doc: "area number or nil"
  attr :target_area, :any, required: true, doc: "area number or nil"

  def world_map(assigns) do
    assigns = assign(assigns, :view_box, Geometry.view_box())

    ~H"""
    <div class="world-map">
      <svg viewBox={@view_box} role="group" aria-label="World map board" class="block h-auto w-full">
        <.original_map_defs />
        <rect class="world-map-sea" x="0" y="0" width="800" height="480" />
        <rect class="world-map-sea-texture" x="0" y="0" width="800" height="480" />
        <use href="#gc-sea-lanes" class="world-map-lanes" />
        <g class="world-map-areas">
          <.territory
            :for={area <- @areas}
            area={area}
            players={@players}
            selected={area.number == @selected_area}
            target={area.number == @target_area}
          />
        </g>
        <use href="#gc-region-outlines" class="world-map-outlines" />
        <g class="world-map-highlights" aria-hidden="true">
          <use :if={@selected_area} href={"#gc-area-#{@selected_area}"} class="world-map-halo" />
          <use
            :if={@selected_area}
            href={"#gc-area-#{@selected_area}"}
            class="world-map-highlight world-map-highlight--selected"
          />
          <use :if={@target_area} href={"#gc-area-#{@target_area}"} class="world-map-halo" />
          <use
            :if={@target_area}
            href={"#gc-area-#{@target_area}"}
            class="world-map-highlight world-map-highlight--target"
          />
        </g>
        <g class="world-map-counts" aria-hidden="true">
          <.army_count :for={area <- @areas} :if={area.armies} area={area} />
        </g>
      </svg>
      <script :type={Phoenix.LiveView.ColocatedHook} name=".TerritoryKeyboard">
        // SVG has no <button>, so a territory is a focusable role="button" <g>;
        // this gives it the keyboard activation a real button has for free.
        // Clicks go through phx-click on the same element — this hook only
        // covers Enter/Space (Space must be swallowed or the page scrolls).
        export default {
          mounted() {
            this.el.addEventListener("keydown", (e) => {
              if (e.key === "Enter" || e.key === " ") {
                e.preventDefault()
                this.pushEvent("select_area", {area: this.el.dataset.area})
              }
            })
          }
        }
      </script>
    </div>
    """
  end

  attr :area, :map, required: true
  attr :players, :list, required: true
  attr :selected, :boolean, required: true
  attr :target, :boolean, required: true

  defp territory(assigns) do
    assigns = assign(assigns, :label, territory_label(assigns.area, assigns.players))

    ~H"""
    <g
      id={"territory-#{@area.number}"}
      class="world-map-territory"
      role="button"
      tabindex="0"
      aria-label={@label}
      aria-pressed={to_string(@selected or @target)}
      data-area={@area.number}
      data-owner={owner_slot(@area)}
      data-fog={!@area.visible}
      phx-hook=".TerritoryKeyboard"
      phx-click="select_area"
      phx-value-area={@area.number}
    >
      <title>{@label}</title>
      <use href={"#gc-area-#{@area.number}"} class="world-map-area" />
    </g>
    """
  end

  attr :area, :map, required: true

  defp army_count(assigns) do
    {x, y} = Geometry.label(assigns.area.number)
    assigns = assign(assigns, x: x, y: y)

    ~H"""
    <text x={@x} y={@y} class="world-map-count" text-anchor="middle" dominant-baseline="central">
      {@area.armies}
    </text>
    """
  end

  # Mirrors the sprite board's `owner_number % 9` colour slot (`Player.GetColor()`
  # in the original), so `--map-owner-N` tokens line up with the legacy palette
  # order players may remember. Fog-hidden areas get no slot at all — the fog
  # hatch is styled off `data-fog`, never off a neutral "0" that would be
  # indistinguishable from a genuinely unclaimed territory (GIF-121).
  defp owner_slot(%{visible: false}), do: nil
  defp owner_slot(%{owner_number: nil}), do: 0
  defp owner_slot(%{owner_number: number}), do: rem(number, 9)

  defp territory_label(%{visible: false} = area, _players),
    do: "#{area.name}, hidden by fog of war"

  defp territory_label(area, players) do
    owner =
      case Enum.find(players, &(&1.number == area.owner_number)) do
        %{name: name} -> "owned by #{name}"
        nil -> "unclaimed"
      end

    "#{area.name}, #{owner}, #{armies_text(area.armies)}"
  end

  defp armies_text(1), do: "1 army"
  defp armies_text(n), do: "#{n} armies"
end
