import Config

# Configure your database
# Ports follow the fleet's block scheme (the fleet's port registry): this
# project owns block 11400 — 11400 web, 11410 gRPC engine, 11434 mysql.
config :global_combat, GlobalCombat.Repo,
  username: System.get_env("MYSQL_USER", "root"),
  password: System.get_env("MYSQL_PASSWORD", ""),
  hostname: System.get_env("MYSQL_HOST", "localhost"),
  port: String.to_integer(System.get_env("MYSQL_PORT", "11434")),
  database: "global_combat_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :global_combat, GlobalCombatWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Inside the dev container this must be 0.0.0.0 for the published port to
  # reach the process at all; the docker-compose port mapping is itself
  # bound to 127.0.0.1, so the no-LAN-access guarantee still holds.
  http: [
    ip: if(System.get_env("PHX_BIND") == "all", do: {0, 0, 0, 0}, else: {127, 0, 0, 1}),
    port: 11400
  ],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "xOy8Kbu2BXe2EZT1pOQYv/I+GwlFpC27dZBqZ5BPRr+CNU5vR0GTav5TgwJGODDo",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:global_combat, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:global_combat, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :global_combat, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
